package example.model;

import java.math.BigDecimal;
import java.util.Date;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.name
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.real_name
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.status
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.phone
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.unionid
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private String unionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.unionid_ding_talk
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private String unionidDingTalk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.mp_openid
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private String mpOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.wx_openid
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private String wxOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.wechat_openid
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private String wechatOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.token
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.token_h5
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private String tokenH5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.token_wechat
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private String tokenWechat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.token_yatai
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private String tokenYatai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.token_ding_talk
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private String tokenDingTalk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.sex
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Byte sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.birthday
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.country
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.province
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.city
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.transaction_amount
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private BigDecimal transactionAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.transaction_count
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Integer transactionCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.vip
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Integer vip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.score
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.balance
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private BigDecimal balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.balance_third
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private BigDecimal balanceThird;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.email
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.avatar
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.signature
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private String signature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.repo_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Integer repoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.region_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Integer regionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.picker_name
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private String pickerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.picker_phone
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private String pickerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.picker_addr
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private String pickerAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.address_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Integer addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.employee_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.up_uid
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Long upUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.real_up_uid
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Long realUpUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.up_uid_time
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Date upUidTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.show_spread
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Boolean showSpread;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.last_login_ip
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private String lastLoginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.last_login_time
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.time
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.spread_num
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Integer spreadNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.rebate_total
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private BigDecimal rebateTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.rebate_taken
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private BigDecimal rebateTaken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.rebate_left
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private BigDecimal rebateLeft;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.rebate_consumed
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private BigDecimal rebateConsumed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.order_popup
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Boolean orderPopup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.ykt_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Integer yktId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.ykt_account_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Integer yktAccountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.pay_type
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Integer payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.balance_enable
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Boolean balanceEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.user_device_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Integer userDeviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.channel
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private String channel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.family_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Long familyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.callback_group_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Integer callbackGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.get_callback_reward
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Byte getCallbackReward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.personal_balance
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private BigDecimal personalBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.company_balance
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private BigDecimal companyBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.quota_balance
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private BigDecimal quotaBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.company_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.employee_type
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private Byte employeeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.vip_offer
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private BigDecimal vipOffer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.im_password
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    private String imPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.id
     *
     * @return the value of t_users.id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.id
     *
     * @param id the value for t_users.id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.name
     *
     * @return the value of t_users.name
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.name
     *
     * @param name the value for t_users.name
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.real_name
     *
     * @return the value of t_users.real_name
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.real_name
     *
     * @param realName the value for t_users.real_name
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.status
     *
     * @return the value of t_users.status
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.status
     *
     * @param status the value for t_users.status
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.phone
     *
     * @return the value of t_users.phone
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.phone
     *
     * @param phone the value for t_users.phone
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.unionid
     *
     * @return the value of t_users.unionid
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.unionid
     *
     * @param unionid the value for t_users.unionid
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setUnionid(String unionid) {
        this.unionid = unionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.unionid_ding_talk
     *
     * @return the value of t_users.unionid_ding_talk
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public String getUnionidDingTalk() {
        return unionidDingTalk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.unionid_ding_talk
     *
     * @param unionidDingTalk the value for t_users.unionid_ding_talk
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setUnionidDingTalk(String unionidDingTalk) {
        this.unionidDingTalk = unionidDingTalk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.mp_openid
     *
     * @return the value of t_users.mp_openid
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public String getMpOpenid() {
        return mpOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.mp_openid
     *
     * @param mpOpenid the value for t_users.mp_openid
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setMpOpenid(String mpOpenid) {
        this.mpOpenid = mpOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.wx_openid
     *
     * @return the value of t_users.wx_openid
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public String getWxOpenid() {
        return wxOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.wx_openid
     *
     * @param wxOpenid the value for t_users.wx_openid
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setWxOpenid(String wxOpenid) {
        this.wxOpenid = wxOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.wechat_openid
     *
     * @return the value of t_users.wechat_openid
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public String getWechatOpenid() {
        return wechatOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.wechat_openid
     *
     * @param wechatOpenid the value for t_users.wechat_openid
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setWechatOpenid(String wechatOpenid) {
        this.wechatOpenid = wechatOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.token
     *
     * @return the value of t_users.token
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.token
     *
     * @param token the value for t_users.token
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.token_h5
     *
     * @return the value of t_users.token_h5
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public String getTokenH5() {
        return tokenH5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.token_h5
     *
     * @param tokenH5 the value for t_users.token_h5
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setTokenH5(String tokenH5) {
        this.tokenH5 = tokenH5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.token_wechat
     *
     * @return the value of t_users.token_wechat
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public String getTokenWechat() {
        return tokenWechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.token_wechat
     *
     * @param tokenWechat the value for t_users.token_wechat
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setTokenWechat(String tokenWechat) {
        this.tokenWechat = tokenWechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.token_yatai
     *
     * @return the value of t_users.token_yatai
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public String getTokenYatai() {
        return tokenYatai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.token_yatai
     *
     * @param tokenYatai the value for t_users.token_yatai
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setTokenYatai(String tokenYatai) {
        this.tokenYatai = tokenYatai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.token_ding_talk
     *
     * @return the value of t_users.token_ding_talk
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public String getTokenDingTalk() {
        return tokenDingTalk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.token_ding_talk
     *
     * @param tokenDingTalk the value for t_users.token_ding_talk
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setTokenDingTalk(String tokenDingTalk) {
        this.tokenDingTalk = tokenDingTalk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.sex
     *
     * @return the value of t_users.sex
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.sex
     *
     * @param sex the value for t_users.sex
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.birthday
     *
     * @return the value of t_users.birthday
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.birthday
     *
     * @param birthday the value for t_users.birthday
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.country
     *
     * @return the value of t_users.country
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.country
     *
     * @param country the value for t_users.country
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.province
     *
     * @return the value of t_users.province
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.province
     *
     * @param province the value for t_users.province
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.city
     *
     * @return the value of t_users.city
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.city
     *
     * @param city the value for t_users.city
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.transaction_amount
     *
     * @return the value of t_users.transaction_amount
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public BigDecimal getTransactionAmount() {
        return transactionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.transaction_amount
     *
     * @param transactionAmount the value for t_users.transaction_amount
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setTransactionAmount(BigDecimal transactionAmount) {
        this.transactionAmount = transactionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.transaction_count
     *
     * @return the value of t_users.transaction_count
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Integer getTransactionCount() {
        return transactionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.transaction_count
     *
     * @param transactionCount the value for t_users.transaction_count
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setTransactionCount(Integer transactionCount) {
        this.transactionCount = transactionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.vip
     *
     * @return the value of t_users.vip
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Integer getVip() {
        return vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.vip
     *
     * @param vip the value for t_users.vip
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setVip(Integer vip) {
        this.vip = vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.score
     *
     * @return the value of t_users.score
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.score
     *
     * @param score the value for t_users.score
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.balance
     *
     * @return the value of t_users.balance
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.balance
     *
     * @param balance the value for t_users.balance
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.balance_third
     *
     * @return the value of t_users.balance_third
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public BigDecimal getBalanceThird() {
        return balanceThird;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.balance_third
     *
     * @param balanceThird the value for t_users.balance_third
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setBalanceThird(BigDecimal balanceThird) {
        this.balanceThird = balanceThird;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.email
     *
     * @return the value of t_users.email
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.email
     *
     * @param email the value for t_users.email
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.avatar
     *
     * @return the value of t_users.avatar
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.avatar
     *
     * @param avatar the value for t_users.avatar
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.signature
     *
     * @return the value of t_users.signature
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.signature
     *
     * @param signature the value for t_users.signature
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setSignature(String signature) {
        this.signature = signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.repo_id
     *
     * @return the value of t_users.repo_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Integer getRepoId() {
        return repoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.repo_id
     *
     * @param repoId the value for t_users.repo_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setRepoId(Integer repoId) {
        this.repoId = repoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.region_id
     *
     * @return the value of t_users.region_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.region_id
     *
     * @param regionId the value for t_users.region_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.picker_name
     *
     * @return the value of t_users.picker_name
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public String getPickerName() {
        return pickerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.picker_name
     *
     * @param pickerName the value for t_users.picker_name
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setPickerName(String pickerName) {
        this.pickerName = pickerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.picker_phone
     *
     * @return the value of t_users.picker_phone
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public String getPickerPhone() {
        return pickerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.picker_phone
     *
     * @param pickerPhone the value for t_users.picker_phone
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setPickerPhone(String pickerPhone) {
        this.pickerPhone = pickerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.picker_addr
     *
     * @return the value of t_users.picker_addr
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public String getPickerAddr() {
        return pickerAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.picker_addr
     *
     * @param pickerAddr the value for t_users.picker_addr
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setPickerAddr(String pickerAddr) {
        this.pickerAddr = pickerAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.address_id
     *
     * @return the value of t_users.address_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.address_id
     *
     * @param addressId the value for t_users.address_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.employee_id
     *
     * @return the value of t_users.employee_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.employee_id
     *
     * @param employeeId the value for t_users.employee_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.up_uid
     *
     * @return the value of t_users.up_uid
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Long getUpUid() {
        return upUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.up_uid
     *
     * @param upUid the value for t_users.up_uid
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setUpUid(Long upUid) {
        this.upUid = upUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.real_up_uid
     *
     * @return the value of t_users.real_up_uid
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Long getRealUpUid() {
        return realUpUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.real_up_uid
     *
     * @param realUpUid the value for t_users.real_up_uid
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setRealUpUid(Long realUpUid) {
        this.realUpUid = realUpUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.up_uid_time
     *
     * @return the value of t_users.up_uid_time
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Date getUpUidTime() {
        return upUidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.up_uid_time
     *
     * @param upUidTime the value for t_users.up_uid_time
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setUpUidTime(Date upUidTime) {
        this.upUidTime = upUidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.show_spread
     *
     * @return the value of t_users.show_spread
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Boolean getShowSpread() {
        return showSpread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.show_spread
     *
     * @param showSpread the value for t_users.show_spread
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setShowSpread(Boolean showSpread) {
        this.showSpread = showSpread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.last_login_ip
     *
     * @return the value of t_users.last_login_ip
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.last_login_ip
     *
     * @param lastLoginIp the value for t_users.last_login_ip
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.last_login_time
     *
     * @return the value of t_users.last_login_time
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.last_login_time
     *
     * @param lastLoginTime the value for t_users.last_login_time
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.time
     *
     * @return the value of t_users.time
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.time
     *
     * @param time the value for t_users.time
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.spread_num
     *
     * @return the value of t_users.spread_num
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Integer getSpreadNum() {
        return spreadNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.spread_num
     *
     * @param spreadNum the value for t_users.spread_num
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setSpreadNum(Integer spreadNum) {
        this.spreadNum = spreadNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.rebate_total
     *
     * @return the value of t_users.rebate_total
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public BigDecimal getRebateTotal() {
        return rebateTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.rebate_total
     *
     * @param rebateTotal the value for t_users.rebate_total
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setRebateTotal(BigDecimal rebateTotal) {
        this.rebateTotal = rebateTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.rebate_taken
     *
     * @return the value of t_users.rebate_taken
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public BigDecimal getRebateTaken() {
        return rebateTaken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.rebate_taken
     *
     * @param rebateTaken the value for t_users.rebate_taken
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setRebateTaken(BigDecimal rebateTaken) {
        this.rebateTaken = rebateTaken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.rebate_left
     *
     * @return the value of t_users.rebate_left
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public BigDecimal getRebateLeft() {
        return rebateLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.rebate_left
     *
     * @param rebateLeft the value for t_users.rebate_left
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setRebateLeft(BigDecimal rebateLeft) {
        this.rebateLeft = rebateLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.rebate_consumed
     *
     * @return the value of t_users.rebate_consumed
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public BigDecimal getRebateConsumed() {
        return rebateConsumed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.rebate_consumed
     *
     * @param rebateConsumed the value for t_users.rebate_consumed
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setRebateConsumed(BigDecimal rebateConsumed) {
        this.rebateConsumed = rebateConsumed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.order_popup
     *
     * @return the value of t_users.order_popup
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Boolean getOrderPopup() {
        return orderPopup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.order_popup
     *
     * @param orderPopup the value for t_users.order_popup
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setOrderPopup(Boolean orderPopup) {
        this.orderPopup = orderPopup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.ykt_id
     *
     * @return the value of t_users.ykt_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Integer getYktId() {
        return yktId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.ykt_id
     *
     * @param yktId the value for t_users.ykt_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setYktId(Integer yktId) {
        this.yktId = yktId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.ykt_account_id
     *
     * @return the value of t_users.ykt_account_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Integer getYktAccountId() {
        return yktAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.ykt_account_id
     *
     * @param yktAccountId the value for t_users.ykt_account_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setYktAccountId(Integer yktAccountId) {
        this.yktAccountId = yktAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.pay_type
     *
     * @return the value of t_users.pay_type
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.pay_type
     *
     * @param payType the value for t_users.pay_type
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.balance_enable
     *
     * @return the value of t_users.balance_enable
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Boolean getBalanceEnable() {
        return balanceEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.balance_enable
     *
     * @param balanceEnable the value for t_users.balance_enable
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setBalanceEnable(Boolean balanceEnable) {
        this.balanceEnable = balanceEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.user_device_id
     *
     * @return the value of t_users.user_device_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Integer getUserDeviceId() {
        return userDeviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.user_device_id
     *
     * @param userDeviceId the value for t_users.user_device_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setUserDeviceId(Integer userDeviceId) {
        this.userDeviceId = userDeviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.channel
     *
     * @return the value of t_users.channel
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.channel
     *
     * @param channel the value for t_users.channel
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setChannel(String channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.family_id
     *
     * @return the value of t_users.family_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Long getFamilyId() {
        return familyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.family_id
     *
     * @param familyId the value for t_users.family_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setFamilyId(Long familyId) {
        this.familyId = familyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.callback_group_id
     *
     * @return the value of t_users.callback_group_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Integer getCallbackGroupId() {
        return callbackGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.callback_group_id
     *
     * @param callbackGroupId the value for t_users.callback_group_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setCallbackGroupId(Integer callbackGroupId) {
        this.callbackGroupId = callbackGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.get_callback_reward
     *
     * @return the value of t_users.get_callback_reward
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Byte getGetCallbackReward() {
        return getCallbackReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.get_callback_reward
     *
     * @param getCallbackReward the value for t_users.get_callback_reward
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setGetCallbackReward(Byte getCallbackReward) {
        this.getCallbackReward = getCallbackReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.personal_balance
     *
     * @return the value of t_users.personal_balance
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public BigDecimal getPersonalBalance() {
        return personalBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.personal_balance
     *
     * @param personalBalance the value for t_users.personal_balance
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setPersonalBalance(BigDecimal personalBalance) {
        this.personalBalance = personalBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.company_balance
     *
     * @return the value of t_users.company_balance
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public BigDecimal getCompanyBalance() {
        return companyBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.company_balance
     *
     * @param companyBalance the value for t_users.company_balance
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setCompanyBalance(BigDecimal companyBalance) {
        this.companyBalance = companyBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.quota_balance
     *
     * @return the value of t_users.quota_balance
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public BigDecimal getQuotaBalance() {
        return quotaBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.quota_balance
     *
     * @param quotaBalance the value for t_users.quota_balance
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setQuotaBalance(BigDecimal quotaBalance) {
        this.quotaBalance = quotaBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.company_id
     *
     * @return the value of t_users.company_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.company_id
     *
     * @param companyId the value for t_users.company_id
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.employee_type
     *
     * @return the value of t_users.employee_type
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public Byte getEmployeeType() {
        return employeeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.employee_type
     *
     * @param employeeType the value for t_users.employee_type
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setEmployeeType(Byte employeeType) {
        this.employeeType = employeeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.vip_offer
     *
     * @return the value of t_users.vip_offer
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public BigDecimal getVipOffer() {
        return vipOffer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.vip_offer
     *
     * @param vipOffer the value for t_users.vip_offer
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setVipOffer(BigDecimal vipOffer) {
        this.vipOffer = vipOffer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.im_password
     *
     * @return the value of t_users.im_password
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public String getImPassword() {
        return imPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.im_password
     *
     * @param imPassword the value for t_users.im_password
     *
     * @mbg.generated Fri Mar 19 17:52:41 CST 2021
     */
    public void setImPassword(String imPassword) {
        this.imPassword = imPassword;
    }
}